import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Append(CPPPATH = ['#xcommon', '#xnetwork'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xclient_exe_name = 'xclient'
xclient_exe = xenv.BuildProgram(xclient_exe_name, sources)

SConscript('unit_tests/SConscript', ['xenv'])
