import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Prepend(CPPPATH = ['#xcommon', '#xnetwork'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

xagent_sources = ['xagent.cpp', 'xagent_var_init.cpp']
xagent_sources = [os.path.join('#xagent', file) for file in xagent_sources]

xenv.Append(CPPPATH = ['#xagent'])
xagent_objects = xenv.LocalObjects(xagent_sources)

sources = xenv.Glob('*.cpp')
xchat_server_exe_name = 'xchat_server'
xchat_server_exe = xenv.BuildProgram(xchat_server_exe_name, sources + xagent_objects)

SConscript('unit_tests/SConscript', ['xenv'])
