import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Prepend(CPPPATH = ['#xcommon'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xnetwork_lib_name = 'xnetwork'
xnetwork_lib = xenv.BuildStaticLibrary(xnetwork_lib_name, sources)

SConscript('unit_tests/SConscript', ['xenv'])

Return(['xnetwork_lib'])
