import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Append(CPPPATH = ['../xcommon'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xnet_messages_lib_name = 'xnet_messages'
xnet_messages_lib = xenv.BuildStaticLibrary(xnet_messages_lib_name, sources)

SConscript('unit_tests/SConscript', ['xenv'])

Return(['xnet_messages_lib'])
