import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Prepend(CPPPATH = ['#xcommon'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xenv_exe_name = 'xenv'
xenv_exe = xenv.BuildProgram(xenv_exe_name, sources)
