import os

Import('xenv')
Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

xenv.Prepend(CPPPATH = ['#xcommon', '#xnetwork'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xagent_exe_name = 'xagent'
xagent_exe = xenv.BuildProgram(xagent_exe_name, sources)

SConscript('unit_tests/SConscript', ['xenv'])
