Import('xenv')

xenv = xenv.Clone()
xenv.UseGoogleMock()
xenv.Append(CPPPATH = ['..'])
sources = xenv.Glob('*.cpp')
xagent_unit_tests_name = 'xagent_tests'
xagent_unit_tests = xenv.BuildProgram(xagent_unit_tests_name, sources + xenv.GoogleMockObjects())
xenv.RunTest(xagent_unit_tests)
