import os

Import('xenv')
#Import('libs')

xenv = xenv.Clone()
xenv.UseBoost()

#xenv.Append(CPPPATH = ['#xcommon'], LIBS = [os.path.splitext(lib.name)[0] for lib in libs], LIBPATH = [lib.dir for lib in libs])

sources = xenv.Glob('*.cpp')
xuuid_exe_name = 'xuuid'
xuuid_exe = xenv.BuildProgram(xuuid_exe_name, sources)
